### ISSUE TITLE
extend channel name recognition schema for flood and fire alarm

### ISSUE THREAD

**Issue by chris299** [ioBroker/ioBroker.type-detector#38]
**Describe the bug**  
currently alias "floodalarm" channel type is not recognized being a flood alarm.

**Expected behavior**  
add "floodalarm" to regex in line 572 (also for firealarm similar)

**Screenshots & Logfiles**  
![1694715356581-6e5831ca-8a5a-4f64-ae82-15ab68ec0f5d-grafik](https://github.com/ioBroker/ioBroker.type-detector/assets/33319001/70d2d5d9-37e6-4553-96af-f74db66938ab)

![1694715423599-521fdd15-4108-49e9-8710-7b1aff923d5e-grafik](https://github.com/ioBroker/ioBroker.type-detector/assets/33319001/552ff823-24db-43e3-a239-49a28cf6b12a)

**Comment by Garfonso** [comment]
TBH I'd remove the channelRole requirement for floodAlarm (and also fireAlarm), because the regex is specific enough. Not? It will only accept roles with "flood" (or "fire") at the end.

@GermanBluefox since you introduced the devices originally, what is your opinion? Why did you add the channelRole requirement back then? Some Homematic devices?
